/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CountryCountryIdImport } from './routes/country.$countryId'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const CountryCountryIdRoute = CountryCountryIdImport.update({
  id: '/country/$countryId',
  path: '/country/$countryId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/country/$countryId': {
      id: '/country/$countryId'
      path: '/country/$countryId'
      fullPath: '/country/$countryId'
      preLoaderRoute: typeof CountryCountryIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/country/$countryId': typeof CountryCountryIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/country/$countryId': typeof CountryCountryIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/country/$countryId': typeof CountryCountryIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/country/$countryId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/country/$countryId'
  id: '__root__' | '/' | '/country/$countryId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CountryCountryIdRoute: typeof CountryCountryIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CountryCountryIdRoute: CountryCountryIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/country/$countryId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/country/$countryId": {
      "filePath": "country.$countryId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
